spring:
 #gzip压缩配置优化调用
  compression:
    enabled: true
    mime-types: application/json ,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048 #默认就是2048 byte
  # 重试
  cloud:
    loadbalancer:
      retry:
        enabled: true

  security:
    user:
      name: admin
      password: 1qaz_QAZ
  servlet:
    multipart: #上传文件配置
      maxFileSize: 20MB #设置文件大小 20MB 不限制设置-1
      maxRequestSize: 20MB #设置请求大小 20MB 不限制设置-1


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


eureka:
# 实例配置类： EurekaInstanceConfigBean
  instance:

     # 设置微服务调用地址为IP优先（缺省为false）
#    perferIpAddress: true
    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}
     # 心跳时间，即服务续约间隔时间（缺省为30s）
#    leaseRenewalIntervalInSeconds: 10
    lease-renewal-interval-in-seconds: 5
     # 发呆时间，即服务续约到期时间（缺省为90s）
    lease-expiration-duration-in-seconds: 30


    # 客户端配置类： EurekaClientConfigBean
  client:
    #从eureka服务器注册表中获取注册信息的时间间隔（s），默认为30秒
    registryFetchIntervalSeconds: 5
    #是否从服务注册中心获取可用的服务清单，默认为true
    fetch-registry: true
    #是否将自己注册到eureka服务注册中心，默认为true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:17001/eureka-server/eureka/



# 全局ribbon配置
ribbon:
  ConnectTimeout: 4000 #请求连接的超时时间
  ReadTimeout: 4000 #请求处理的超时时间
  OkToRetryOnAllOperations: true #对所有操作请求都进行重试
  MaxAutoRetriesNextServer: 1 #切换实例的重试次数
  MaxAutoRetries: 1 #对当前实例的重试次数


# feign配置
feign:
  hystrix:
    # 打开feign的hystrix功能
    enabled: true



#logback中配置的日志路径
logback:
  logfile:
    path: /data/logs/${spring.application.name}
